# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

intraLaplacian <- function(mod) {
    .Call('_nettools_intraLaplacian', PACKAGE = 'nettools', mod)
}

directProd <- function(Li, n) {
    .Call('_nettools_directProd', PACKAGE = 'nettools', Li, n)
}

IntraAdj <- function(mod) {
    .Call('_nettools_IntraAdj', PACKAGE = 'nettools', mod)
}

