# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

intraLaplacian <- function(mod) {
    .Call('nettools_intraLaplacian', PACKAGE = 'nettools', mod)
}

directProd <- function(Li, n) {
    .Call('nettools_directProd', PACKAGE = 'nettools', Li, n)
}

